In [1]:
# numpy ndarray
import numpy as np

# generate some random data
data = np.random.randn(2,3)
data

array([[ 0.39183965, -0.08711642, -0.08213105],
       [-0.79554015, -1.82859473, -1.06407143]])

In [2]:
data * 10

array([[  3.9183965 ,  -0.87116425,  -0.82131049],
       [ -7.95540149, -18.28594727, -10.64071429]])

In [3]:
data + data

array([[ 0.7836793 , -0.17423285, -0.1642621 ],
       [-1.5910803 , -3.65718945, -2.12814286]])

In [4]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [7]:
# list to ndarray
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2, 3, 2))

array([[[1.16527166e-311, 0.00000000e+000],
        [4.94065646e-324, 4.94065646e-324],
        [1.16528672e-311, 4.94065646e-324]],

       [[1.16528702e-311, 1.16528702e-311],
        [0.00000000e+000, 2.49009086e-321],
        [9.88131292e-324, 1.16528702e-311]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

In [21]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [23]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [27]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [29]:
arr = np.arange(10)
arr[5]
arr[5:8]

array([5, 6, 7])

In [30]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [32]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [34]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [38]:
arr2d[0][2]

3

In [40]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[1, 0]

array([7, 8, 9])

In [47]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [48]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [49]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [52]:
arr2d[1, :2]

array([4, 5])

In [53]:
arr2d[:2, 2]

array([3, 6])

In [54]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [56]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [60]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array([[ 0.62345189, -1.33229758, -0.78901106, -0.92135981],
       [-0.0175679 , -0.20593436, -0.44881038, -0.36516066],
       [ 0.1986339 ,  1.37819902, -0.43752436,  0.16288658],
       [ 2.190364  ,  0.33863434, -0.32606576,  0.43898005],
       [-0.52693963, -2.06320979,  1.90210871,  1.48979172],
       [ 0.70609137, -2.55901409,  0.17195069,  0.29057878],
       [-0.16762752, -0.66158617, -0.08716133, -0.93258428]])

In [61]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [66]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [67]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 25.37930726, -14.71415519,  33.7856847 ,  -8.18990313,
        -20.50873916],
       [-14.71415519,   9.64010022, -21.10123016,   5.32768244,
         13.40634709],
       [ 33.7856847 , -21.10123016,  47.48272294, -11.81372406,
        -29.63739743],
       [ -8.18990313,   5.32768244, -11.81372406,   3.26277501,
          7.6924701 ],
       [-20.50873916,  13.40634709, -29.63739743,   7.6924701 ,
         19.21302779]])

In [68]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -3.19890209e-15,  1.10994383e-14,
        -3.36508777e-16, -5.64053128e-17],
       [ 5.28069689e-15,  1.00000000e+00,  1.05820526e-14,
         2.89789830e-15, -8.87872954e-15],
       [ 1.04274400e-14,  3.29442408e-15,  1.00000000e+00,
         2.24516348e-15, -7.66974408e-15],
       [ 2.58742281e-16,  1.28969598e-15,  3.37538558e-15,
         1.00000000e+00, -2.31490184e-15],
       [-2.54365896e-15, -9.97197348e-16, -3.78013464e-15,
        -7.31353037e-16,  1.00000000e+00]])

In [70]:
q, r = qr(mat)
r

array([[-2.38841336,  3.05356985,  4.3997343 , -1.53064811,  2.73831364],
       [ 0.        , -5.90400222, -0.91306012, -2.96462611,  3.92293044],
       [ 0.        ,  0.        , -0.67341589,  1.88345119, -1.82766587],
       [ 0.        ,  0.        ,  0.        , -5.15807821,  2.06215064],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.02289926]])

In [72]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.56024589,  0.16764796, -0.88538681, -0.00802898],
       [ 0.64124549, -0.69584867, -0.02696689, -0.35592733],
       [ 1.27155963,  0.38694424,  0.45072235, -1.10718654],
       [-0.94669143, -0.26395711, -1.25943078, -1.69608283]])

In [ ]:
np.random.seed(1234)
rng = np.random.RandomState(1234)
rng.randn(10)